#spring.application.name=gateway-service
#eureka.client.service-url.defaulZone=http://localhost:8761/eukera

server:
  port: 8080

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: server2
          uri: http://localhost:2222/
          predicates:
            - Path=/service2
        - id: service3
          uri: http://localhost:3333/
          predicates:
            - Path=/service3
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
